# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS Terraform Deploy

on:
  push:
    branches: [ "new_branch" ]
on:
  workflow_dispatch:
# on:
#   pull_request:
#     branches: [ "main" ]
#     types: [ "closed" ]
#     workflow_dispatch:


env:
    AWS_REGION : "ap-south-1"
    AWS_OIDC_ROLE : "arn:aws:iam::087843402575:role/github_oidc_role"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  Terraform-aws-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials DEV env
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: aws_tf
        run: terraform init -reconfigure

      - name: Terraform Plan
        id: plan
        working-directory: aws_tf
        run: terraform plan -out=tfplan-${{ github.sha }}


      - name: Apply Terraform
        if: success()
        working-directory: aws_tf
        run: terraform destroy -auto-approve